-- `ifp-operation`.spc_point_metadata definition

-- `ifp-operation`.spc_point_metadata definition

CREATE TABLE `spc_point_metadata` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `measure_code` varchar(64) NOT NULL COMMENT '点位唯一标识',
  `measure_name` varchar(128) NOT NULL COMMENT '点位名称',
  `job_id` varchar(50) NOT NULL COMMENT '作业ID/产线ID',
  `indicator_name` varchar(100) NOT NULL COMMENT '指标名称（业务唯一标识）',
  `indicator_level` varchar(20) NOT NULL COMMENT '指标级别（A/B/C 级）',
  `class_code` varchar(50) NOT NULL COMMENT '所属科室/部门编码',
  `area_code` varchar(32) DEFAULT NULL COMMENT '区域编码',
  `system_code` varchar(32) NOT NULL COMMENT '系统编码',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `data_type` varchar(16) DEFAULT 'analog' COMMENT '数据类型：analog/digital',
  `precision_decimal` int(11) DEFAULT '2' COMMENT '数值精度（小数位）',
  `range_min` decimal(15,6) DEFAULT NULL COMMENT '量程最小值',
  `range_max` decimal(15,6) DEFAULT NULL COMMENT '量程最大值',
  `y_axis_min` decimal(15,6) DEFAULT NULL COMMENT 'Y轴显示最小值',
  `y_axis_max` decimal(15,6) DEFAULT NULL COMMENT 'Y轴显示最大值',
  `y_axis_step` decimal(15,6) DEFAULT NULL COMMENT 'Y轴刻度步长',
  `enable_realtime_alarm` tinyint(1) DEFAULT '0' COMMENT '是否启用实时SPC',
  `enable_offline_chart` tinyint(1) DEFAULT '1' COMMENT '是否允许创建离线控制图',
  `target_value` decimal(18,3) DEFAULT NULL COMMENT '目标值',
  `ucl_value` decimal(18,3) DEFAULT NULL COMMENT '控制线上限值',
  `lcl_value` decimal(18,3) DEFAULT NULL COMMENT '控制线下限值',
  `uwl_value` decimal(18,3) DEFAULT NULL COMMENT '警告线上限值',
  `lwl_value` decimal(18,3) DEFAULT NULL COMMENT '警告线下限值',
  `usl_value` decimal(18,3) DEFAULT NULL COMMENT '规格线上限值',
  `lsl_value` decimal(18,3) DEFAULT NULL COMMENT '规格线下限值',
  `u3l_value` decimal(18,3) DEFAULT NULL COMMENT '3σ上限值(R1规则）',
  `l3l_value` decimal(18,3) DEFAULT NULL COMMENT '3σ下限值(R1规则）',
  `equipment_id` varchar(64) DEFAULT NULL COMMENT '设备ID',
  `equipment_name` varchar(128) DEFAULT NULL COMMENT '设备名称',
  `department` varchar(32) DEFAULT NULL COMMENT '科室/部门',
  `ocap_template_id` varchar(100) DEFAULT NULL COMMENT 'OCAP流程模板ID',
  `enabled_sampling_status` tinyint(1) DEFAULT '0' COMMENT 'SPC采样策略总开关',
  `enabled_spc_controlled` tinyint(1) DEFAULT '0' COMMENT 'SPC监控总开关',
  `attributes` json DEFAULT NULL COMMENT '扩展属性（自定义字段）',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `fac_code` varchar(32) DEFAULT NULL COMMENT '厂区编码',
  `config_type` varchar(100) DEFAULT NULL COMMENT '配置来源(USER,SYSTEM)',
  `is_default` tinyint(1) DEFAULT '0' COMMENT '是否默认配置(0:否,1:是)',
  `deleted_id` bigint(20) DEFAULT '0' COMMENT '逻辑删除标识',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签（多个标签用逗号分隔）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `spc_point_metadata_unique` (`job_id`,`deleted_id`),
  KEY `idx_plant_area_system` (`fac_code`,`area_code`,`system_code`),
  KEY `idx_equipment` (`equipment_id`),
  KEY `idx_status` (`enabled_spc_controlled`,`enabled_sampling_status`),
  KEY `idx_job_id` (`job_id`),
  KEY `idx_class_code` (`class_code`),
  KEY `idx_deleted` (`deleted_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SPC 点位元数据表（V2）';

-- `ifp-operation`.spc_sampling_strategy definition
-- `ifp-operation`.spc_sampling_strategy definition

CREATE TABLE `spc_sampling_strategy` (
 `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
 `measure_code` varchar(64) NOT NULL COMMENT '指标编码',
 `job_id` varchar(128) DEFAULT NULL COMMENT '作业ID，关联spc_point_metadata表的job_id',
 `period_s` int(11) NOT NULL COMMENT '采样周期（秒）：60/300/3600',
 `period_label` varchar(16) DEFAULT '1m' COMMENT '周期标签：1m/5m/1h',
 `strategy_type` varchar(16) DEFAULT 'periodic' COMMENT '策略类型：periodic/change/threshold/hybrid',
 `window_type` varchar(16) DEFAULT 'tumble' COMMENT '窗口类型：tumble/hop/session',
 `window_size_s` int(11) DEFAULT '60' COMMENT '窗口大小（秒）；periodic默认=period_s；hop用作INTERVAL',
 `slide_step_s` int(11) DEFAULT NULL COMMENT '窗口滑动步长（秒），仅hop生效（SLIDING）',
 `session_gap_s` int(11) DEFAULT NULL COMMENT '会话窗口gap（秒），仅session生效',
 `deadband_abs` decimal(15,6) DEFAULT NULL COMMENT '绝对死区',
 `deadband_percent` decimal(5,2) DEFAULT NULL COMMENT '相对死区（%）',
 `max_interval_s` int(11) DEFAULT NULL COMMENT '最大采样间隔（秒）',
 `threshold_upper` decimal(15,6) DEFAULT NULL COMMENT '上阈值',
 `threshold_lower` decimal(15,6) DEFAULT NULL COMMENT '下阈值',
 `normal_period_s` int(11) DEFAULT NULL COMMENT '正常采样周期',
 `alert_period_s` int(11) DEFAULT NULL COMMENT '告警采样周期',
 `alert_duration_s` int(11) DEFAULT NULL COMMENT '告警模式持续时间',
 `features` varchar(128) DEFAULT 'first,last,avg,max,min,std' COMMENT '统计特征（逗号分隔）',
 `computation_mode` varchar(16) DEFAULT 'realtime' COMMENT '计算方式：realtime/batch/hybrid',
 `value_mode` varchar(16) NOT NULL DEFAULT 'avg' COMMENT '样本值口径：avg/last/median',
 `subgroup_window_s` int(11) DEFAULT NULL COMMENT '子组窗口秒数（Xbar-R用），推荐60',
 `min_valid_n` int(11) DEFAULT NULL COMMENT '子组最小有效点数（baseline/图控），默认4',
 `valid_ratio_min` decimal(4,2) DEFAULT NULL COMMENT '有效比例阈值（baseline），默认0.80',
 `drift_ratio_max` decimal(6,4) DEFAULT NULL COMMENT '子组内漂移阈值（baseline），默认0.0100',
 `baseline_window_days` int(11) NOT NULL DEFAULT '7' COMMENT '基线计算窗口天数（rolling）',
 `baseline_refresh_s` int(11) NOT NULL DEFAULT '3600' COMMENT '基线刷新周期（秒）',
 `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
 `priority` int(11) DEFAULT '0' COMMENT '优先级（数字越大优先级越高）',
 `physical_limit_enabled` tinyint(4) DEFAULT '1' COMMENT '异常数据处理:是否启用物理上下限守卫（0=关闭,1=开启）',
 `physical_min_value` decimal(20,6) DEFAULT NULL COMMENT '异常数据处理:物理下限值（NULL表示不限制）',
 `physical_max_value` decimal(20,6) DEFAULT NULL COMMENT '异常数据处理:物理上限值（NULL表示不限制）',
 `out_of_range_action` varchar(64) DEFAULT 'drop' COMMENT '异常数据处理:越界值处理方式（drop=丢弃,clip=裁剪到边界,mark=标记但保留）',
 `outlier_detection_method` varchar(64) DEFAULT 'none' COMMENT '异常数据处理:离群值检测方法（仅用于基线计算）enum(''none'',''3sigma'',''median'',''iqr'',''hampel'')',
 `outlier_3sigma_threshold` decimal(5,2) DEFAULT '3.00' COMMENT '异常数据处理:3σ方法：异常阈值倍数（默认3.0）',
 `outlier_3sigma_iterations` int(11) DEFAULT '2' COMMENT '异常数据处理:3σ方法：迭代次数（1-3，默认2）',
 `outlier_median_threshold` decimal(5,2) DEFAULT '3.00' COMMENT '异常数据处理:中位数方法：MAD倍数阈值（默认3.0）',
 `outlier_median_window` int(11) DEFAULT '7' COMMENT '异常数据处理:中位数方法：滑动窗口大小（默认7）',
 `outlier_iqr_k` decimal(5,2) DEFAULT '1.50' COMMENT '异常数据处理:IQR方法：四分位数范围倍数K（默认1.5）',
 `outlier_hampel_k` decimal(5,2) DEFAULT '3.00' COMMENT '异常数据处理:Hampel方法：阈值K（默认3.0）',
 `outlier_hampel_window` int(11) DEFAULT '7' COMMENT '异常数据处理:Hampel方法：滑动窗口大小（默认7）',
 `outlier_action` varchar(64) DEFAULT 'drop' COMMENT '异常数据处理:检测到离群值的处理方式enum(''drop'',''mark'',''keep'')',
 `quality_filter_enabled` tinyint(1) DEFAULT '1' COMMENT '异常数据处理:是否启用质量码过滤（0=关闭,1=开启）',
 `quality_allowed_codes` varchar(50) DEFAULT '192' COMMENT '异常数据处理:允许的质量码列表，逗号分隔（默认仅好值192）',
 `bad_value_action` varchar(64) DEFAULT 'drop' COMMENT '异常数据处理:坏值处理方式（drop=丢弃,mark=标记,keep=保留）',
 `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
 `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
 `fac_code` varchar(32) DEFAULT NULL COMMENT '厂区编码',
 PRIMARY KEY (`id`),
 UNIQUE KEY `uk_point_period` (`measure_code`,`period_s`),
 KEY `idx_strategy_type` (`strategy_type`),
 KEY `idx_enabled` (`enabled`),
 KEY `idx_spc_sampling_strategy_job_id` (`job_id`),
 KEY `idx_spc_sampling_strategy_job_id_period` (`job_id`,`period_s`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SPC 采样策略配置表';


-- `ifp-operation`.spc_chart_config definition

CREATE TABLE `spc_chart_config` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `point_id` varchar(64) NOT NULL COMMENT '点位ID',
    `chart_type` varchar(16) NOT NULL COMMENT '控制图类型：I-MR/EWMA/Xbar-R/CUSUM/p/c/u',
    `chart_name` varchar(128) DEFAULT NULL COMMENT '控制图名称',
    `baseline_window_days` int(11) DEFAULT '7' COMMENT '基线窗口天数（7/14/30）',
    `baseline_update_freq` varchar(16) DEFAULT 'daily' COMMENT '基线更新频率：hourly/daily/weekly',
    `baseline_version` varchar(32) DEFAULT NULL COMMENT '当前基线版本',
    `limit_calc_mode` enum('auto','manual','hybrid') DEFAULT 'auto' COMMENT '控制限计算模式：auto=基线自动计算, manual=手动固定, hybrid=混合',
    `use_3sigma` tinyint(1) DEFAULT '1' COMMENT '是否使用 3σ 控制限',
    `sigma_multiplier` decimal(3,1) DEFAULT '3.0' COMMENT 'σ 倍数（通常为 3.0）',
    `ucl` decimal(15,6) DEFAULT NULL COMMENT '固定控制上限（UCL）',
    `lcl` decimal(15,6) DEFAULT NULL COMMENT '固定控制下限（LCL）',
    `uwl` decimal(15,6) DEFAULT NULL COMMENT '固定警告上限（UWL）',
    `lwl` decimal(15,6) DEFAULT NULL COMMENT '固定警告下限（LWL）',
    `usl` decimal(15,6) DEFAULT NULL COMMENT '上规格限（USL）',
    `lsl` decimal(15,6) DEFAULT NULL COMMENT '下规格限（LSL）',
    `target_value` decimal(15,6) DEFAULT NULL COMMENT '目标值（Target）',
    `rule_r1_enabled` tinyint(1) DEFAULT '1' COMMENT 'R1: 单点超出 3σ',
    `rule_r2_enabled` tinyint(1) DEFAULT '1' COMMENT 'R2: 连续 9 点同侧',
    `rule_r3_enabled` tinyint(1) DEFAULT '1' COMMENT 'R3: 连续 6 点递增/递减',
    `rule_r4_enabled` tinyint(1) DEFAULT '1' COMMENT 'R4: 连续 14 点交替',
    `rule_r5_enabled` tinyint(1) DEFAULT '1' COMMENT 'R5: 3 点中 2 点超 2σ',
    `rule_r6_enabled` tinyint(1) DEFAULT '1' COMMENT 'R6: 5 点中 4 点超 1σ',
    `rule_r7_enabled` tinyint(1) DEFAULT '1' COMMENT 'R7: 15 点在 1σ 内',
    `rule_r8_enabled` tinyint(1) DEFAULT '1' COMMENT 'R8: 8 点在 1σ 外',
    `alarm_enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用告警',
    `alarm_severity` tinyint(4) DEFAULT '2' COMMENT '告警严重度（1-4）',
    `enabled` tinyint(1) DEFAULT '1' COMMENT '是否启用',
    `status` varchar(16) DEFAULT 'active' COMMENT '状态：active/inactive',
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_point_chart` (`point_id`,`chart_type`),
    KEY `idx_chart_type` (`chart_type`),
    KEY `idx_enabled` (`enabled`),
    KEY `idx_limit_calc_mode` (`limit_calc_mode`),
    CONSTRAINT `spc_chart_config_ibfk_1` FOREIGN KEY (`point_id`) REFERENCES `spc_sampling_strategy` (`measure_code`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SPC 控制图配置表（V2）';